name: Deploy Custom RG Roles

on:
  push:
    branches:
      - main

permissions:           # 👈 required for OIDC
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login (OIDC)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}       # App Registration Client ID
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}       # Directory (Tenant) ID
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy RG Admin Role
      run: |
        echo "Deploying Custom RG Admin Role..."
        az role definition create --role-definition roles/mp-rg-admin.json || \
        az role definition update --role-definition roles/mp-rg-admin.json

    - name: Deploy RG Reader Role
      run: |
        echo "Deploying Custom RG Reader Role..."
        az role definition create --role-definition roles/mp-rg-reader.json || \
        az role definition update --role-definition roles/mp-rg-reader.json
